version: "3.8"

services:
  fdi:
    image: africahazardswatch/fdi:latest
    container_name: fdi
    build: .
    restart: ${RESTART_POLICY}
    env_file:
      - .env
    volumes:
      - ${DATA_VOLUME}:/home/node/app/public/fdi
      - ${DATA_STATE_VOLUME}:/home/node/app/src/state
  fdi_web_proxy:
      image: nginx:1.23.1-alpine
      container_name: fdi_web_proxy
      restart: ${RESTART_POLICY}
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        - ${DATA_VOLUME}:/data
      ports:
        - ${NGINX_PUBLIC_PORT}:80

networks:
    default:
      name:  ${AHW_DOCKER_NETWORK}
      external: true