version: "3.8"

services:
  fdi:
    image: africahazardswatch/fdi:latest
    container_name: fdi
    build: .
    restart: ${RESTART_POLICY}
    command: npm start
    volumes:
      - ${DATA_VOLUME}:/app/public
      - ./state:/app/src/state